import type { ProjectPlan } from "../useCases/generateProjectPlan";
import type { FileRoadmap } from "../useCases/generateFileRoadmap";

export const DEMO_PLAN: ProjectPlan = {
  projectName: "FreelanceHub",
  phases: [
    {
      id: 1,
      name: "Fundamentos",
      description: "Autenticación, modelo de datos, API base y estructura del proyecto.",
      duration: "2 semanas",
    },
    {
      id: 2,
      name: "Core Features",
      description: "Perfiles de freelancer, publicación de proyectos, sistema de propuestas y chat.",
      duration: "4 semanas",
    },
    {
      id: 3,
      name: "Pagos y Contratos",
      description: "Integración con Stripe, escrow de pagos, contratos digitales y facturación.",
      duration: "3 semanas",
    },
    {
      id: 4,
      name: "Producción",
      description: "Optimización, tests E2E, monitoreo y despliegue en producción.",
      duration: "2 semanas",
    },
  ],
  techStack: {
    frontend: ["Next.js 15", "TypeScript", "Tailwind CSS", "Zustand", "React Query"],
    backend: ["Node.js", "Fastify", "Zod", "Prisma ORM"],
    database: ["PostgreSQL", "Redis", "Cloudinary"],
    devops: ["Docker", "GitHub Actions", "Vercel", "Railway", "Sentry"],
  },
  tasks: [
    {
      id: 1,
      title: "Diseñar esquema de base de datos",
      description: "Modelar entidades User, FreelancerProfile, Project, Proposal, Contract y Payment con relaciones y restricciones de integridad.",
      phase: "Fundamentos",
      priority: "alta",
      estimatedHours: 6,
    },
    {
      id: 2,
      title: "Implementar autenticación con NextAuth",
      description: "Login con email/contraseña y OAuth (Google, GitHub), refresh tokens, middleware de autorización por roles (client/freelancer/admin).",
      phase: "Fundamentos",
      priority: "alta",
      estimatedHours: 10,
    },
    {
      id: 3,
      title: "Crear API REST base con Fastify",
      description: "Configurar servidor Fastify con plugins de CORS, rate limiting, validación Zod y manejo centralizado de errores.",
      phase: "Fundamentos",
      priority: "alta",
      estimatedHours: 8,
    },
    {
      id: 4,
      title: "Sistema de perfiles de freelancer",
      description: "CRUD de perfil con habilidades, portafolio, tarifas por hora, valoración media y verificación de identidad.",
      phase: "Core Features",
      priority: "alta",
      estimatedHours: 12,
    },
    {
      id: 5,
      title: "Publicación y búsqueda de proyectos",
      description: "Formulario de publicación, búsqueda full-text con filtros (categoría, presupuesto, duración), paginación y ordenación.",
      phase: "Core Features",
      priority: "alta",
      estimatedHours: 14,
    },
    {
      id: 6,
      title: "Sistema de propuestas",
      description: "Envío de propuestas con carta de presentación y precio, gestión de estados (pendiente/aceptada/rechazada) y notificaciones.",
      phase: "Core Features",
      priority: "alta",
      estimatedHours: 10,
    },
    {
      id: 7,
      title: "Chat en tiempo real",
      description: "Mensajería entre cliente y freelancer con Socket.io, historial persistente, indicador de escritura y adjuntos.",
      phase: "Core Features",
      priority: "media",
      estimatedHours: 16,
    },
    {
      id: 8,
      title: "Integración con Stripe",
      description: "Pagos con tarjeta, sistema de escrow (retención hasta entrega), payouts automáticos y webhooks de confirmación.",
      phase: "Pagos y Contratos",
      priority: "alta",
      estimatedHours: 18,
    },
    {
      id: 9,
      title: "Contratos digitales",
      description: "Generación de contratos PDF a partir de plantillas, firma digital y almacenamiento en Cloudinary.",
      phase: "Pagos y Contratos",
      priority: "media",
      estimatedHours: 10,
    },
    {
      id: 10,
      title: "Sistema de valoraciones y reseñas",
      description: "Valoraciones bidireccionales (cliente↔freelancer) al cerrar contrato, puntuación acumulada y moderación.",
      phase: "Pagos y Contratos",
      priority: "media",
      estimatedHours: 8,
    },
    {
      id: 11,
      title: "Tests E2E con Playwright",
      description: "Cubrir flujos críticos: registro, publicar proyecto, enviar propuesta, pago y cierre de contrato.",
      phase: "Producción",
      priority: "alta",
      estimatedHours: 12,
    },
    {
      id: 12,
      title: "Monitoreo y despliegue",
      description: "Configurar Sentry para errores, pipeline CI/CD con GitHub Actions, despliegue en Vercel (frontend) y Railway (backend).",
      phase: "Producción",
      priority: "alta",
      estimatedHours: 8,
    },
  ],
};

export const DEMO_ROADMAP: FileRoadmap = {
  files: [
    { path: "src/domain/entities/User.ts", description: "Entidad User con tipos, roles y reglas de negocio del dominio.", layer: "domain" },
    { path: "src/domain/entities/Project.ts", description: "Entidad Project con estados del ciclo de vida y validaciones.", layer: "domain" },
    { path: "src/domain/entities/Proposal.ts", description: "Entidad Proposal con máquina de estados (pending/accepted/rejected).", layer: "domain" },
    { path: "src/domain/repositories/IUserRepository.ts", description: "Interfaz del repositorio de usuarios que implementará la capa de infraestructura.", layer: "domain" },
    { path: "src/domain/repositories/IProjectRepository.ts", description: "Interfaz del repositorio de proyectos con métodos de búsqueda y filtrado.", layer: "domain" },
    { path: "src/application/useCases/createProject.ts", description: "Caso de uso: valida datos, aplica reglas de negocio y persiste un nuevo proyecto.", layer: "application" },
    { path: "src/application/useCases/submitProposal.ts", description: "Caso de uso: verifica elegibilidad del freelancer y registra la propuesta.", layer: "application" },
    { path: "src/application/useCases/processPayment.ts", description: "Caso de uso: orquesta el flujo de pago con Stripe y actualiza el estado del contrato.", layer: "application" },
    { path: "src/application/dto/ProjectDTO.ts", description: "Data Transfer Objects para creación y actualización de proyectos.", layer: "application" },
    { path: "src/infrastructure/db/prisma/schema.prisma", description: "Esquema Prisma con todos los modelos, relaciones e índices.", layer: "infrastructure" },
    { path: "src/infrastructure/repositories/UserRepository.ts", description: "Implementación concreta de IUserRepository usando Prisma.", layer: "infrastructure" },
    { path: "src/infrastructure/repositories/ProjectRepository.ts", description: "Implementación concreta de IProjectRepository con búsqueda full-text.", layer: "infrastructure" },
    { path: "src/infrastructure/services/StripeService.ts", description: "Wrapper de la API de Stripe: pagos, escrow, payouts y webhooks.", layer: "infrastructure" },
    { path: "src/infrastructure/services/SocketService.ts", description: "Servidor Socket.io para mensajería y notificaciones en tiempo real.", layer: "infrastructure" },
    { path: "src/presentation/components/ProjectCard.tsx", description: "Card de proyecto con presupuesto, categoría, número de propuestas y CTA.", layer: "presentation" },
    { path: "src/presentation/components/ProposalForm.tsx", description: "Formulario controlado para enviar propuesta con validación de cliente.", layer: "presentation" },
    { path: "src/presentation/components/ChatWindow.tsx", description: "Ventana de chat con scroll infinito, estado de conexión y adjuntos.", layer: "presentation" },
    { path: "src/presentation/components/RatingModal.tsx", description: "Modal de valoración al cierre de contrato con puntuación por estrellas.", layer: "presentation" },
    { path: "app/(auth)/login/page.tsx", description: "Página de login con NextAuth, OAuth providers y manejo de errores.", layer: "presentation" },
    { path: "app/(dashboard)/projects/page.tsx", description: "Listado de proyectos con filtros, búsqueda y paginación del lado servidor.", layer: "presentation" },
    { path: "app/(dashboard)/projects/[id]/page.tsx", description: "Detalle de proyecto con propuestas, chat y estado del contrato.", layer: "presentation" },
    { path: "app/api/projects/route.ts", description: "Endpoint REST para listar y crear proyectos con validación Zod.", layer: "infrastructure" },
    { path: "app/api/stripe/webhook/route.ts", description: "Receptor de webhooks de Stripe con verificación de firma.", layer: "infrastructure" },
    { path: "next.config.ts", description: "Configuración de Next.js: dominios de imágenes, variables de entorno y rewrites.", layer: "config" },
    { path: "src/lib/auth.ts", description: "Configuración de NextAuth con providers, callbacks y estrategia de sesión JWT.", layer: "config" },
  ],
};
